[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "blake3>=1.0.8",
    "pytest>=8.4.2",
    "titanoboa>=0.2.8",
    "vyper==0.4.3",
]
